### ISSUE TITLE
💬 Friends

### ISSUE THREAD

**Issue by SigureMo** [SigureMo/nyakku.moe#15]
https://sigure.xyz/friends.html

**Comment by heavenly-zy** [comment]
{
   "name": "ClariS",
   "url": "https://wryyy.life/",
   "descripiton": "Querying for a variable and seizing the time",
   "avatar": "https://wryyy.life/avatar.png"
}

我居然是第一Σ(っ °Д °;)っ

**Comment by demigodliu** [comment]
name: Demigodliu
link: https://blog.demigodliu.com/
avatar: https://blog.demigodliu.com/avatar.png
descr: 以梦为马，不负韶华

**Comment by MrXnneHang** [comment]
感谢大佬！
因为博客没有邮件回复所以过来说一声。

**Comment by SigureMo** [comment]
> 因为博客没有邮件回复所以过来说一声。

@MrXnneHang 看看能收到邮件不，我往 GitHub 主页的邮箱发的

另外这里会让所有人都收到邮件的，这个 issue 先 close 了
