### ISSUE TITLE
💬 About

### ISSUE THREAD

**Issue by SigureMo** [SigureMo/nyakku.moe#7]
https://www.sigure.xyz/About.html

**Comment by SigureMo** [comment]
:smile:

**Comment by smallsunnyfox** [comment]
吼吼

**Comment by smallsunnyfox** [comment]
鼠标又好看了

**Comment by SigureMo** [comment]
@smallsunnyfox

> 鼠标又好看了

嘻嘻😝

**Comment by chenweigao** [comment]
博客很好看~ 可以稍微引用一下么 O(∩_∩)O哈哈~

**Comment by SigureMo** [comment]
@chenweigao

> 博客很好看~ 可以稍微引用一下么 O(∩_∩)O哈哈~

谢谢喜欢～

引用的话，这个 repo 除了文章内容，都是随意哒（MIT嘛），文章也只需要注明下出处（CC4.0 BY-SA）就行啦~

**Comment by chenweigao** [comment]
@SigureMo

> @chenweigao
> 
> > 博客很好看~ 可以稍微引用一下么 O(∩_∩)O哈哈~
> 
> 谢谢喜欢～
> 
> 引用的话，这个 repo 除了文章内容，都是随意哒（MIT嘛），文章也只需要注明下出处（CC4.0 BY-SA）就行啦~
> 

可以Q或者wechat请教你一点问题吗(#^.^#)

**Comment by SigureMo** [comment]
@chenweigao

> @SigureMo
> 
> > @chenweigao
> > 
> > > 博客很好看~ 可以稍微引用一下么 O(∩_∩)O哈哈~
> > 
> > 谢谢喜欢～
> > 
> > 引用的话，这个 repo 除了文章内容，都是随意哒（MIT嘛），文章也只需要注明下出处（CC4.0 BY-SA）就行啦~
> > 
> 
> 可以Q或者wechat请教你一点问题吗(#^.^#)

@chenweigao

可以的，右上角就有联系方式

只不过近期比较忙，如果是主题的问题的话，我建议加一下交流群（加我之后拉你就好啦）

**Comment by gitldy1013** [comment]
美滋滋~

**Comment by SigureMo** [comment]
> 美滋滋~

嘻嘻

**Comment by smallsunnyfox** [comment]
我发现Vssue有点小烦，我评论了一条怎么每条评论都给我发邮件qaq

**Comment by SigureMo** [comment]
@smallsunnyfox

咦？我没遇到呀，之前只开了一个issue，你在这篇下面回复我我看下有没有这问题

“[这篇](https://www.sigure.xyz/Posts/24_Git_Collaboration.html#%E5%90%8C%E6%AD%A5%E6%9B%B4%E6%94%B9)”

**Comment by njit-guoxinyu** [comment]
谢谢博主的博客讲解文章，我看到你的文字以后才知道，原来sidebar: "auto"是在Blogconfig里配置的，我原来还以为作者reco的意思是每篇文章都可以设置有无侧边栏呢，弄得我以为出错，删添了好几次node_modules。

**Comment by njit-guoxinyu** [comment]
另外，好像其他文章的Vssue不能用，而且vssue的相互评论又是一条又一条的，很多，很冗杂。建议还是用Valine啦，开起来快一点。

**Comment by SigureMo** [comment]
@njit-guoxinyu

单篇文章与全局的都有的，单篇文章在 `frontmatter` 配置，全局在 `themeConfig` 配置，可以参见 VuePress 官方文档[“自动生成侧边栏”](https://v1.vuepress.vuejs.org/zh/theme/default-theme-config.html#%E8%87%AA%E5%8A%A8%E7%94%9F%E6%88%90%E4%BE%A7%E6%A0%8F)，官方文档内容很清晰的

至于评论嘛，你应该可以 “点击新建 issue” 吧？emmmm 你没有新建 issue 的权限嘛？当初为了测试 Vssue 就暂时用着了，因为一般没人看也没人写评论也就没改了，以后想折腾时候我再考虑考虑:joy:

> 没预览也挺难受的

**Comment by heavenly-zy** [comment]
大佬你的评论区终于好了，呜呜呜，之前一直想给你留言来着

**Comment by SigureMo** [comment]
@heavenly-zy

> 大佬你的评论区终于好了，呜呜呜，之前一直想给你留言来着
> 

:joy: 之前换了主题就一直懒得管啦，前两天重新弄了弄

对了，交换友链不～

**Comment by heavenly-zy** [comment]
@SigureMo

> @heavenly-zy
> 
> > 大佬你的评论区终于好了，呜呜呜，之前一直想给你留言来着
> > 
> 
> :joy: 之前换了主题就一直懒得管啦，前两天重新弄了弄
> 
> 对了，交换友链不～

可以呀，在哪儿弄呀

**Comment by SigureMo** [comment]
@heavenly-zy

我的 Navbar 上的 Friends 里留下言就好啦～emmm，如果你那里本地有我的缓存的话可能找不到 Friends，强制刷新下就好啦～

**Comment by heavenly-zy** [comment]
@SigureMo

> @heavenly-zy
> 
> 我的 Navbar 上的 Friends 里留下言就好啦～emmm，如果你那里本地有我的缓存的话可能找不到 Friends，强制刷新下就好啦～
> 

嗷嗷，看见啦
